
= Tizziano
:lang: it
:author: Tiziano
v1.1, 12-feb-2017
v1.3, 21-aprile-2017
:backend: xhtml11
:base: 
:linkcss:
:stylesdir: {base}risorse/css
:scriptsdir: {base}risorse/javascripts
:stylesheet: tizziano.css
:max-width: 600px; margin: auto;

include::{base}risorse/templates/navbar.template[]

.Prove tecniche di comunicazione

L'obiettivo è di essere in grado di esporre le cose che faccio per 
condividerle. Per questo, aprire semplicemente un archivio GitHub non basta. 
Serve uno spazio web per esporre e illustrare quanto si è fatto, altrimenti non 
c'è comunicazione. 

Al momento sono impegnato in un'impresa piuttosto difficile e noiosa, per 
illustrare il progetto https://tizziano.github.io/mastroPiano[mastroPiano]. 
Altre cose saranno disponibili col tempo, come ad esempio la pagina Blink, 
oppure altre storie, che parleranno di come sia possibile ottenere una pagina 
HTML (oppure un intero sito) da uno o più file di testo e come utilizzare certi 
strumenti software per semplificare, anziché complicare la propria vita e il 
proprio lavoro. 

== Comunicare

Comunicare significa condividere la conoscenza, quindi, se comunico, condivido. 
Una parola! Ma come? Dicono che un'immagine vale mille parole, ma senza una 
breve spiegazione l'immagine mantiene la sua efficacia? 

Mi serve uno strumento per mettere insieme e mostrare in una forma gradevole e 
comprensibile testi e immagini. Già utilizzo per questo l'applicativo 
_LibreOffice_, ma per produrre materiale cartaceo. Quello che mi serve adesso è 
qualcosa che mi permetta di produrre pagine HTML, come questa. 

== Linguaggio



== Spazio web statico o dinamico




